name: build

on:
  pull_request:
#    branches: ["feature/cicd"]
    branches: [master]
    types: [closed]
  push:
    tags:
      - '*'
    branches:
      - 'master'

jobs:
  build:
    if: github.event.pull_request.merged == true && ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/tags/' }}
    runs-on: macos-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      - name: v
        id: version
        run: |
          VERSION=$(echo "${{ github.head_ref }}" | sed -e 's/^v//')
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"
      - name: 更新文件内容
        uses: fjogeleit/yaml-update-action@v0.13.0
        with:
          valueFile: 'pubspec.yaml'
          propertyPath: 'version'
          value: ${{ steps.version.outputs.version }}
          commitChange: false
      
      - name: Get latest tag
        id: get-latest-tag
        run: |
          git fetch --tags -f
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          VERSION=$(echo "$(latest_tag)" | sed -e 's/^v//')
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"

      - name: Use latest tag
        run: |
          echo "Latest tag is ${{ steps.get-latest-tag.outputs.VERSION }}"

