name: build

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true && ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/tags/' }}
    runs-on: macos-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      - name: 显示文件内容1
        run: cat pubspec.yaml
      - name: 显示版本
        run: |
          echo $GITHUB_HEAD_REF
      - name: 更新文件内容
        uses: fjogeleit/yaml-update-action@v0.13.0
        with:
          valueFile: 'pubspec.yaml'
          propertyPath: 'version'
          value: $GITHUB_HEAD_REF
          commitChange: false
      - name: 显示文件内容2
        run: cat pubspec.yaml
